# Site settings
baseurl = "https://depts.washington.edu/marinepredators/"
languageCode = "en-us"
title = "Marine Predators Group"
theme = "syna"
enableGitInfo = true
version = "0.15.2"

# Google Analytics tracking
googleAnalytics = ""

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[params]
  name = "Marine Predators Group"
  description = "Research group at University of Washington"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "shark_fin-512-hex.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "shark_fin-512-hex.png"
    favicon_svg = "shark_fin-512-hex.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    #primary = "#00838F"
    primary = "#0145B1"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.

[[menu.main]]
  url = "#"
  name = "Home"
  weight = 1
  
[[menu.main]]
  url = "#items"
  name = "Research"
  weight = 10
 
[[menu.main]]
  url = "#member"
  name = "People"
  weight = 20

[[menu.main]]
  url = "publications"
  name = "Publications"
  weight = 30

[[menu.main]]
  url = "https://github.com/marine-predators-group"
  name = "Open science"
  weight = 40

[[menu.main]]
  url = "prospectives"
  name = "Join us"
  weight = 50

[[menu.main]]
  url = "#copyright"
  name = "Contact"
  weight = 60

[[menu.footer]]
  url = "#"
  name = "Link"
  weight = 10

[[menu.footer]]
  url = "#"
  name = "Long Link"
  weight = 30

[[menu.footer]]
  url = "#"
  name = "Tiny Link"
  weight = 30

#[[menu.copyright_footer]]
#  url = "/about"
#  name = "About Us"
#  weight = 10

#[[menu.copyright_footer]]
#  url = "mailto:marinepredators@uw.edu"
#  name = "Contact"
#  weight = 30

#[[menu.footer_social]]
#  weight = 20
#  name = "facebook"
#  pre = "fab fa-facebook-f"
#  url = "#"

#[[menu.footer_social]]
#  weight = 30
#  name = "linkedin"
#  pre = "fab fa-linkedin-in"
#  url = "#"
